# Generated by Django 2.2.10 on 2020-03-11 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(help_text='Descripción de la categoría', max_length=100, unique=True, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(help_text='Descripción de la sub categoría', max_length=100, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Categoria')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('categoria', 'descripcion')},
                'verbose_name': 'Sub Categoria',
                'verbose_name_plural': 'Sub Categorias',
            },
        ),
    ]
