# Generated by Django 2.2.10 on 2020-03-13 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0004_unidadmedida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('codigo_barra', models.CharField(max_length=50, unique=True, verbose_name='Código de barra')),
                ('descripcion', models.CharField(help_text='Descripción del Producto', max_length=200, verbose_name='Descripción')),
                ('precio', models.FloatField(default=0, verbose_name='Precio venta')),
                ('existencia', models.IntegerField(default=0)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Marca')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.SubCategoria', verbose_name='Sub Categoría')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.UnidadMedida', verbose_name='Unidad de medida')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
